[settings]
lockfile = true
experimental = true

[tools]
"aqua:amir20/dtop" = "0.2.0"
"aqua:FairwindsOps/polaris" = "10.1.2"
"aqua:JanDeDobbeleer/oh-my-posh" = "27.5.1"
"aqua:muquit/mailsend-go" = "1.0.10"
"aqua:schollz/croc" = "10.2.7"
"aqua:sibprogrammer/xq" = "1.3.0"
"aqua:zyedidia/micro" = "2.0.14"
#azure = "2.75.0"
aws = "2.31.30"
aws-vault = "7.2.0"
bitwarden = "2025.10.0"
chezmoi = "2.67.0"
cosign = "3.0.2"
doggo = "1.1.2"
fd = "10.3.0"
gh = "2.83.0"
hadolint = "2.14.0"
helm = "3.19.0"
jq = "1.8.1"
k6 = "1.3.0"
kiota = "1.29.0"
kops = "1.34.0"
krew = "0.4.5"
kubectl = "1.34.1"
lazygit = "0.56.0"
minisign = "0.12"
python = "3.14.0"
rclone = "1.71.2"
ripgrep = "15.1.0"
shellcheck = "0.11.0"
sops = "3.11.0"
step = "0.28.7"
task = "3.45.4"
usql = "0.19.26"
xh = "0.25.0"
yq = "4.48.1"
restic = "0.18.1"
