[settings]
lockfile = true
experimental = true

[tools]
"aqua:FairwindsOps/polaris" = "10.1.4"
"aqua:JanDeDobbeleer/oh-my-posh" = "29.4.1"
"aqua:amir20/dtop" = "0.6.12"
"aqua:entireio/cli" = "0.4.5"
"aqua:loft-sh/devpod" = "0.7.0-alpha.34"
"aqua:muquit/mailsend-go" = "1.0.10"
"aqua:schollz/croc" = "10.3.1"
"aqua:sibprogrammer/xq" = "1.3.0"
"aqua:zyedidia/micro" = "2.0.15"
#azure = "2.75.0"
aws = { version = "2.33.25", symlink_bins = "true" }
aws-vault = "7.9.7"
bitwarden = "2026.1.0"
cosign = "3.0.5"
doggo = "1.1.4"
fd = "10.3.0"
gh = "2.87.0"
hadolint = "2.14.0"
helm = "4.1.1"
jq = "1.8.1"
jujutsu = "0.38.0"
k6 = "1.6.1"
kiota = "1.30.0"
kops = "1.34.1"
krew = "0.4.5"
kubectl = "1.35.1"
lazygit = "0.59.0"
minisign = "0.12"
oxker = "0.12.0"
powershell = "7.5.4"
rclone = "1.73.1"
ripgrep = "15.1.0"
shellcheck = "0.11.0"
sops = "3.11.0"
step = "0.29.0"
task = "3.48.0"
usql = "0.20.8"
xh = "0.25.3"
yq = "4.52.4"
