[settings]
lockfile = true
experimental = true

[tools]
"aqua:amir20/dtop" = "0.6.7"
"aqua:FairwindsOps/polaris" = "10.1.3"
"aqua:JanDeDobbeleer/oh-my-posh" = "29.0.1"
"aqua:muquit/mailsend-go" = "1.0.10"
"aqua:schollz/croc" = "10.3.1"
"aqua:sibprogrammer/xq" = "1.3.0"
"aqua:zyedidia/micro" = "2.0.15"
#azure = "2.75.0"
aws = { version = "2.32.31", symlink_bins = "true" }
aws-vault = "7.2.0"
bitwarden = "2025.12.0"
cosign = "3.0.3"
doggo = "1.1.4"
fd = "10.3.0"
gh = "2.83.2"
hadolint = "2.14.0"
helm = "4.0.4"
jq = "1.8.1"
k6 = "1.5.0"
kiota = "1.29.0"
kops = "1.34.1"
krew = "0.4.5"
kubectl = "1.35.0"
lazygit = "0.58.0"
minisign = "0.12"
python = "3.14.2"
powershell = "7.5.4"
rclone = "1.72.1"
ripgrep = "15.1.0"
shellcheck = "0.11.0"
sops = "3.11.0"
step = "0.29.0"
task = "3.46.4"
usql = "0.20.6"
xh = "0.25.3"
yq = "4.50.1"
oxker = "0.12.0"
jujutsu = "0.37.0"
