[settings]
lockfile = true
experimental = true

[tools]
"aqua:amir20/dtop" = "0.6.6"
"aqua:FairwindsOps/polaris" = "10.1.2"
"aqua:JanDeDobbeleer/oh-my-posh" = "28.1.0"
"aqua:muquit/mailsend-go" = "1.0.10"
"aqua:schollz/croc" = "10.3.1"
"aqua:sibprogrammer/xq" = "1.3.0"
"aqua:zyedidia/micro" = "2.0.14"
#azure = "2.75.0"
aws = { version = "2.32.11", symlink_bins = "true" }
aws-vault = "7.2.0"
bitwarden = "2025.11.0"
cosign = "3.0.2"
doggo = "1.1.2"
fd = "10.3.0"
gh = "2.83.1"
hadolint = "2.14.0"
helm = "4.0.1"
jq = "1.8.1"
k6 = "1.4.2"
kiota = "1.29.0"
kops = "1.34.1"
krew = "0.4.5"
kubectl = "1.34.2"
lazygit = "0.57.0"
minisign = "0.12"
python = "3.14.2"
rclone = "1.72.0"
ripgrep = "15.1.0"
shellcheck = "0.11.0"
sops = "3.11.0"
step = "0.29.0"
task = "3.45.5"
usql = "0.19.26"
xh = "0.25.0"
yq = "4.49.2"
oxker = "0.12.0"
jujutsu = "0.36.0"
